<%--flexberryautogenerated="true"--%>
<%@ Page Language="C#" MasterPageFile="~/Site1.Master"  AutoEventWireup="true" CodeBehind="ZayavlenieE.aspx.cs" Inherits="IIS.Rating.ЗаявлениеE" %>
<%@ Import namespace="NewPlatform.Flexberry.Web.Page" %>
<%-- Autogenerated section start [Register] --%>
<%-- Autogenerated section end [Register] --%>

<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <div class="<%= Constants.FormCssClass + " " +  Constants.EditFormCssClass %>">
        <h2 class="<%= Constants.FormHeaderCssClass + " " + Constants.EditFormHeaderCssClass %>">Заявление</h2>
        <div class="<%= Constants.FormToolbarCssClass  + " " +  Constants.EditFormToolbarCssClass + " " + Constants.StickyCssClass %>">
            <asp:ImageButton ID="SaveBtn" runat="server" SkinID="SaveBtn" OnClick="SaveBtn_Click" AlternateText="<%$ Resources: Resource, Save %>" ValidationGroup="savedoc" />
            <asp:ImageButton ID="SaveAndCloseBtn" runat="server" SkinID="SaveAndCloseBtn" OnClick="SaveAndCloseBtn_Click" AlternateText="<%$ Resources: Resource, Save_Close %>" ValidationGroup="savedoc" />
            <asp:ImageButton ID="CancelBtn" runat="server" SkinID="CancelBtn" OnClick="CancelBtn_Click" AlternateText="<%$ Resources: Resource, Cancel %>" />
        </div>
        <div class="<%= Constants.FormControlsCssClass + " " + Constants.EditFormControlsCssClass %>">
            <%-- Autogenerated section start [Controls] --%>
<!-- autogenerated start -->
<div>
	<fieldset ID="ctrl_fsАбитуриент" style="clear: left">
	<legend>Абитуриент</legend>
	<div class="clearfix">
  <asp:Label CssClass="descLbl" ID="ctrlАбитуриентLabel" runat="server" Text="Абитуриент" EnableViewState="False">
</asp:Label>
<ac:MasterEditorAjaxLookUp ID="ctrlАбитуриент" CssClass="descTxt" runat="server" ShowInThickBox="True" Autocomplete="true" />

<asp:RequiredFieldValidator ID="ctrlАбитуриентRequiredFieldValidator" runat="server" ControlToValidate="ctrlАбитуриент"
                            ErrorMessage="Не указано: Абитуриент" Text="*" 
                            EnableClientScript="true" ValidationGroup="savedoc" />

</div>
<div class="clearfix">
  <asp:Label CssClass="descLbl" ID="ctrlАбитуриент_ИмяLabel" runat="server" Text="Абитуриент.Имя" EnableViewState="False">
</asp:Label>
<asp:TextBox CssClass="descTxt" ID="ctrlАбитуриент_Имя" runat="server" ReadOnly="true">
</asp:TextBox>

<asp:RequiredFieldValidator ID="ctrlАбитуриент_ИмяRequiredFieldValidator" runat="server" ControlToValidate="ctrlАбитуриент_Имя"
                            ErrorMessage="Не указано: Абитуриент.Имя" Text="*" 
                            EnableClientScript="true" ValidationGroup="savedoc" />

</div>
<div class="clearfix">
  <asp:Label CssClass="descLbl" ID="ctrlАбитуриент_ОтчествоLabel" runat="server" Text="Абитуриент.Отчество" EnableViewState="False">
</asp:Label>
<asp:TextBox CssClass="descTxt" ID="ctrlАбитуриент_Отчество" runat="server" ReadOnly="true">
</asp:TextBox>

<asp:RequiredFieldValidator ID="ctrlАбитуриент_ОтчествоRequiredFieldValidator" runat="server" ControlToValidate="ctrlАбитуриент_Отчество"
                            ErrorMessage="Не указано: Абитуриент.Отчество" Text="*" 
                            EnableClientScript="true" ValidationGroup="savedoc" />

</div>
<div class="clearfix">
  <asp:Label CssClass="descLbl" ID="ctrlАбитуриент_СреднийБаллАттестатаLabel" runat="server" Text="Аттестат" EnableViewState="False">
</asp:Label>
<ac:DecimalTextBox CssClass="descTxt" ReadOnly="true" ID="ctrlАбитуриент_СреднийБаллАттестата" runat="server">
</ac:DecimalTextBox>

<asp:RequiredFieldValidator ID="ctrlАбитуриент_СреднийБаллАттестатаRequiredFieldValidator" runat="server" ControlToValidate="ctrlАбитуриент_СреднийБаллАттестата"
                            ErrorMessage="Не указано: Абитуриент.СреднийБаллАттестата" Text="*" 
                            EnableClientScript="true" ValidationGroup="savedoc" />

</div>
<div class="clearfix">
  <asp:Label CssClass="descLbl" ID="ctrlАбитуриент_ЭссеLabel" runat="server" Text="Эссе" EnableViewState="False">
</asp:Label>
<ac:AlphaNumericTextBox CssClass="descTxt" ID="ctrlАбитуриент_Эссе" Type="Numeric" runat="server" ReadOnly="true">
</ac:AlphaNumericTextBox>

<asp:RequiredFieldValidator ID="ctrlАбитуриент_ЭссеRequiredFieldValidator" runat="server" ControlToValidate="ctrlАбитуриент_Эссе"
                            ErrorMessage="Не указано: Абитуриент.Эссе" Text="*" 
                            EnableClientScript="true" ValidationGroup="savedoc" />

</div>
<div class="clearfix">
  <asp:Label CssClass="descLbl" ID="ctrlАбитуриент_ДопБаллыLabel" runat="server" Text="Доп.баллы" EnableViewState="False">
</asp:Label>
<ac:AlphaNumericTextBox CssClass="descTxt" ID="ctrlАбитуриент_ДопБаллы" Type="Numeric" runat="server" ReadOnly="true">
</ac:AlphaNumericTextBox>


</div>

</fieldset><fieldset ID="ctrl_fsЗаявление" style="clear: left">
	<legend>Заявление</legend>
	<div class="clearfix">
  <asp:Label CssClass="descLbl" ID="ctrlОценка1Label" runat="server" Text="Оценка1" EnableViewState="False">
</asp:Label>
<ac:AlphaNumericTextBox CssClass="descTxt" ID="ctrlОценка1" Type="Numeric" runat="server">
</ac:AlphaNumericTextBox>

<asp:RequiredFieldValidator ID="ctrlОценка1RequiredFieldValidator" runat="server" ControlToValidate="ctrlОценка1"
                            ErrorMessage="Не указано: Оценка1" Text="*" 
                            EnableClientScript="true" ValidationGroup="savedoc" />

</div>
<div class="clearfix">
  <asp:Label CssClass="descLbl" ID="ctrlОценка2Label" runat="server" Text="Оценка2" EnableViewState="False">
</asp:Label>
<ac:AlphaNumericTextBox CssClass="descTxt" ID="ctrlОценка2" Type="Numeric" runat="server">
</ac:AlphaNumericTextBox>

<asp:RequiredFieldValidator ID="ctrlОценка2RequiredFieldValidator" runat="server" ControlToValidate="ctrlОценка2"
                            ErrorMessage="Не указано: Оценка2" Text="*" 
                            EnableClientScript="true" ValidationGroup="savedoc" />

</div>
<div class="clearfix">
  <asp:Label CssClass="descLbl" ID="ctrlОценка3Label" runat="server" Text="Оценка3" EnableViewState="False">
</asp:Label>
<ac:AlphaNumericTextBox CssClass="descTxt" ID="ctrlОценка3" Type="Numeric" runat="server">
</ac:AlphaNumericTextBox>

<asp:RequiredFieldValidator ID="ctrlОценка3RequiredFieldValidator" runat="server" ControlToValidate="ctrlОценка3"
                            ErrorMessage="Не указано: Оценка3" Text="*" 
                            EnableClientScript="true" ValidationGroup="savedoc" />

</div>
<div class="clearfix">
  <asp:Label CssClass="descLbl" ID="ctrlНаправлениеLabel" runat="server" Text="Направление" EnableViewState="False">
</asp:Label>
<ac:MasterEditorAjaxLookUp ID="ctrlНаправление" CssClass="descTxt" runat="server" ShowInThickBox="True" Autocomplete="true" />

<asp:RequiredFieldValidator ID="ctrlНаправлениеRequiredFieldValidator" runat="server" ControlToValidate="ctrlНаправление"
                            ErrorMessage="Не указано: Направление" Text="*" 
                            EnableClientScript="true" ValidationGroup="savedoc" />

</div>
<div class="clearfix">
  <asp:Label CssClass="descLbl" ID="ctrlФормаОбученияLabel" runat="server" Text="Форма обучения" EnableViewState="False">
</asp:Label>
<ac:MasterEditorAjaxLookUp ID="ctrlФормаОбучения" CssClass="descTxt" runat="server" ShowInThickBox="True" Autocomplete="true" />

<asp:RequiredFieldValidator ID="ctrlФормаОбученияRequiredFieldValidator" runat="server" ControlToValidate="ctrlФормаОбучения"
                            ErrorMessage="Не указано: ФормаОбучения" Text="*" 
                            EnableClientScript="true" ValidationGroup="savedoc" />

</div>
<div class="clearfix">
  <asp:Label CssClass="descLbl" ID="ctrlТипДокументовLabel" runat="server" Text="Тип документов" EnableViewState="False">
</asp:Label>
<ac:MasterEditorAjaxLookUp ID="ctrlТипДокументов" CssClass="descTxt" runat="server" ShowInThickBox="True" Autocomplete="true" />

<asp:RequiredFieldValidator ID="ctrlТипДокументовRequiredFieldValidator" runat="server" ControlToValidate="ctrlТипДокументов"
                            ErrorMessage="Не указано: ТипДокументов" Text="*" 
                            EnableClientScript="true" ValidationGroup="savedoc" />

</div>
<div class="clearfix">
  <asp:Label CssClass="descLbl" ID="ctrlПриоритетLabel" runat="server" Text="Приоритет" EnableViewState="False">
</asp:Label>
<ac:AlphaNumericTextBox CssClass="descTxt" ID="ctrlПриоритет" Type="Numeric" runat="server">
</ac:AlphaNumericTextBox>


</div>

</fieldset>
</div>
<!-- autogenerated end -->
            <%-- Autogenerated section end [Controls] --%>
        </div>
    </div>
</asp:Content>
