//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Rating
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Абитуриент.
    /// </summary>
    // *** Start programmer edit section *** (Абитуриент CustomAttributes)

    // *** End programmer edit section *** (Абитуриент CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("АбитуриентE", new string[] {
            "Фамилия as \'Фамилия\'",
            "Имя as \'Имя\'",
            "Отчество as \'Отчество\'",
            "Паспорт as \'Паспорт (серия/номер)\'",
            "Телефон as \'Номер телефона\'",
            "СреднийБаллАттестата as \'Средний балл аттестата\'",
            "Эссе as \'Эссе\'",
            "ДопБаллы as \'Доп баллы\'"})]
    [View("АбитуриентL", new string[] {
            "Фамилия as \'Фамилия\'",
            "Имя as \'Имя\'",
            "Отчество as \'Отчество\'",
            "СреднийБаллАттестата as \'Средний балл аттестата\'",
            "Эссе as \'Эссе\'",
            "ДопБаллы as \'Доп баллы\'",
            "Телефон as \'Номер телефона\'",
            "Паспорт as \'Паспорт (серия/номер)\'"})]
    public class Абитуриент : ICSSoft.STORMNET.DataObject
    {
        
        private string fФамилия;
        
        private string fИмя;
        
        private string fОтчество;
        
        private string fПаспорт;
        
        private double fСреднийБаллАттестата;
        
        private int fЭссе;
        
        private int fДопБаллы;
        
        private string fТелефон;
        
        // *** Start programmer edit section *** (Абитуриент CustomMembers)

        // *** End programmer edit section *** (Абитуриент CustomMembers)

        
        /// <summary>
        /// Фамилия.
        /// </summary>
        // *** Start programmer edit section *** (Абитуриент.Фамилия CustomAttributes)

        // *** End programmer edit section *** (Абитуриент.Фамилия CustomAttributes)
        [StrLen(255)]
        [NotNull()]
        public virtual string Фамилия
        {
            get
            {
                // *** Start programmer edit section *** (Абитуриент.Фамилия Get start)

                // *** End programmer edit section *** (Абитуриент.Фамилия Get start)
                string result = this.fФамилия;
                // *** Start programmer edit section *** (Абитуриент.Фамилия Get end)

                // *** End programmer edit section *** (Абитуриент.Фамилия Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Абитуриент.Фамилия Set start)

                // *** End programmer edit section *** (Абитуриент.Фамилия Set start)
                this.fФамилия = value;
                // *** Start programmer edit section *** (Абитуриент.Фамилия Set end)

                // *** End programmer edit section *** (Абитуриент.Фамилия Set end)
            }
        }
        
        /// <summary>
        /// Имя.
        /// </summary>
        // *** Start programmer edit section *** (Абитуриент.Имя CustomAttributes)

        // *** End programmer edit section *** (Абитуриент.Имя CustomAttributes)
        [StrLen(255)]
        [NotNull()]
        public virtual string Имя
        {
            get
            {
                // *** Start programmer edit section *** (Абитуриент.Имя Get start)

                // *** End programmer edit section *** (Абитуриент.Имя Get start)
                string result = this.fИмя;
                // *** Start programmer edit section *** (Абитуриент.Имя Get end)

                // *** End programmer edit section *** (Абитуриент.Имя Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Абитуриент.Имя Set start)

                // *** End programmer edit section *** (Абитуриент.Имя Set start)
                this.fИмя = value;
                // *** Start programmer edit section *** (Абитуриент.Имя Set end)

                // *** End programmer edit section *** (Абитуриент.Имя Set end)
            }
        }
        
        /// <summary>
        /// Отчество.
        /// </summary>
        // *** Start programmer edit section *** (Абитуриент.Отчество CustomAttributes)

        // *** End programmer edit section *** (Абитуриент.Отчество CustomAttributes)
        [StrLen(255)]
        [NotNull()]
        public virtual string Отчество
        {
            get
            {
                // *** Start programmer edit section *** (Абитуриент.Отчество Get start)

                // *** End programmer edit section *** (Абитуриент.Отчество Get start)
                string result = this.fОтчество;
                // *** Start programmer edit section *** (Абитуриент.Отчество Get end)

                // *** End programmer edit section *** (Абитуриент.Отчество Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Абитуриент.Отчество Set start)

                // *** End programmer edit section *** (Абитуриент.Отчество Set start)
                this.fОтчество = value;
                // *** Start programmer edit section *** (Абитуриент.Отчество Set end)

                // *** End programmer edit section *** (Абитуриент.Отчество Set end)
            }
        }
        
        /// <summary>
        /// Паспорт.
        /// </summary>
        // *** Start programmer edit section *** (Абитуриент.Паспорт CustomAttributes)

        // *** End programmer edit section *** (Абитуриент.Паспорт CustomAttributes)
        [StrLen(255)]
        [NotNull()]
        public virtual string Паспорт
        {
            get
            {
                // *** Start programmer edit section *** (Абитуриент.Паспорт Get start)

                // *** End programmer edit section *** (Абитуриент.Паспорт Get start)
                string result = this.fПаспорт;
                // *** Start programmer edit section *** (Абитуриент.Паспорт Get end)

                // *** End programmer edit section *** (Абитуриент.Паспорт Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Абитуриент.Паспорт Set start)

                // *** End programmer edit section *** (Абитуриент.Паспорт Set start)
                this.fПаспорт = value;
                // *** Start programmer edit section *** (Абитуриент.Паспорт Set end)

                // *** End programmer edit section *** (Абитуриент.Паспорт Set end)
            }
        }
        
        /// <summary>
        /// СреднийБаллАттестата.
        /// </summary>
        // *** Start programmer edit section *** (Абитуриент.СреднийБаллАттестата CustomAttributes)

        // *** End programmer edit section *** (Абитуриент.СреднийБаллАттестата CustomAttributes)
        [NotNull()]
        public virtual double СреднийБаллАттестата
        {
            get
            {
                // *** Start programmer edit section *** (Абитуриент.СреднийБаллАттестата Get start)

                // *** End programmer edit section *** (Абитуриент.СреднийБаллАттестата Get start)
                double result = this.fСреднийБаллАттестата;
                // *** Start programmer edit section *** (Абитуриент.СреднийБаллАттестата Get end)

                // *** End programmer edit section *** (Абитуриент.СреднийБаллАттестата Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Абитуриент.СреднийБаллАттестата Set start)

                // *** End programmer edit section *** (Абитуриент.СреднийБаллАттестата Set start)
                this.fСреднийБаллАттестата = value;
                // *** Start programmer edit section *** (Абитуриент.СреднийБаллАттестата Set end)

                // *** End programmer edit section *** (Абитуриент.СреднийБаллАттестата Set end)
            }
        }
        
        /// <summary>
        /// Эссе.
        /// </summary>
        // *** Start programmer edit section *** (Абитуриент.Эссе CustomAttributes)

        // *** End programmer edit section *** (Абитуриент.Эссе CustomAttributes)
        [NotNull()]
        public virtual int Эссе
        {
            get
            {
                // *** Start programmer edit section *** (Абитуриент.Эссе Get start)

                // *** End programmer edit section *** (Абитуриент.Эссе Get start)
                int result = this.fЭссе;
                // *** Start programmer edit section *** (Абитуриент.Эссе Get end)

                // *** End programmer edit section *** (Абитуриент.Эссе Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Абитуриент.Эссе Set start)

                // *** End programmer edit section *** (Абитуриент.Эссе Set start)
                this.fЭссе = value;
                // *** Start programmer edit section *** (Абитуриент.Эссе Set end)

                // *** End programmer edit section *** (Абитуриент.Эссе Set end)
            }
        }
        
        /// <summary>
        /// ДопБаллы.
        /// </summary>
        // *** Start programmer edit section *** (Абитуриент.ДопБаллы CustomAttributes)

        // *** End programmer edit section *** (Абитуриент.ДопБаллы CustomAttributes)
        public virtual int ДопБаллы
        {
            get
            {
                // *** Start programmer edit section *** (Абитуриент.ДопБаллы Get start)

                // *** End programmer edit section *** (Абитуриент.ДопБаллы Get start)
                int result = this.fДопБаллы;
                // *** Start programmer edit section *** (Абитуриент.ДопБаллы Get end)

                // *** End programmer edit section *** (Абитуриент.ДопБаллы Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Абитуриент.ДопБаллы Set start)

                // *** End programmer edit section *** (Абитуриент.ДопБаллы Set start)
                this.fДопБаллы = value;
                // *** Start programmer edit section *** (Абитуриент.ДопБаллы Set end)

                // *** End programmer edit section *** (Абитуриент.ДопБаллы Set end)
            }
        }
        
        /// <summary>
        /// Телефон.
        /// </summary>
        // *** Start programmer edit section *** (Абитуриент.Телефон CustomAttributes)

        // *** End programmer edit section *** (Абитуриент.Телефон CustomAttributes)
        [StrLen(255)]
        [NotNull()]
        public virtual string Телефон
        {
            get
            {
                // *** Start programmer edit section *** (Абитуриент.Телефон Get start)

                // *** End programmer edit section *** (Абитуриент.Телефон Get start)
                string result = this.fТелефон;
                // *** Start programmer edit section *** (Абитуриент.Телефон Get end)

                // *** End programmer edit section *** (Абитуриент.Телефон Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Абитуриент.Телефон Set start)

                // *** End programmer edit section *** (Абитуриент.Телефон Set start)
                this.fТелефон = value;
                // *** Start programmer edit section *** (Абитуриент.Телефон Set end)

                // *** End programmer edit section *** (Абитуриент.Телефон Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "АбитуриентE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View АбитуриентE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("АбитуриентE", typeof(IIS.Rating.Абитуриент));
                }
            }
            
            /// <summary>
            /// "АбитуриентL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View АбитуриентL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("АбитуриентL", typeof(IIS.Rating.Абитуриент));
                }
            }
        }
    }
}
