//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Rating
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Все предметы.
    /// </summary>
    // *** Start programmer edit section *** (ВсеПредметы CustomAttributes)

    // *** End programmer edit section *** (ВсеПредметы CustomAttributes)
    [AutoAltered()]
    [Caption("Все предметы")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ВсеПредметыE", new string[] {
            "Название as \'Название\'"})]
    [View("ВсеПредметыL", new string[] {
            "Название as \'Название\'"})]
    public class ВсеПредметы : ICSSoft.STORMNET.DataObject
    {
        
        private string fНазвание;
        
        // *** Start programmer edit section *** (ВсеПредметы CustomMembers)

        // *** End programmer edit section *** (ВсеПредметы CustomMembers)

        
        /// <summary>
        /// Название.
        /// </summary>
        // *** Start programmer edit section *** (ВсеПредметы.Название CustomAttributes)

        // *** End programmer edit section *** (ВсеПредметы.Название CustomAttributes)
        [StrLen(255)]
        [NotNull()]
        public virtual string Название
        {
            get
            {
                // *** Start programmer edit section *** (ВсеПредметы.Название Get start)

                // *** End programmer edit section *** (ВсеПредметы.Название Get start)
                string result = this.fНазвание;
                // *** Start programmer edit section *** (ВсеПредметы.Название Get end)

                // *** End programmer edit section *** (ВсеПредметы.Название Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ВсеПредметы.Название Set start)

                // *** End programmer edit section *** (ВсеПредметы.Название Set start)
                this.fНазвание = value;
                // *** Start programmer edit section *** (ВсеПредметы.Название Set end)

                // *** End programmer edit section *** (ВсеПредметы.Название Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ВсеПредметыE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ВсеПредметыE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ВсеПредметыE", typeof(IIS.Rating.ВсеПредметы));
                }
            }
            
            /// <summary>
            /// "ВсеПредметыL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ВсеПредметыL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ВсеПредметыL", typeof(IIS.Rating.ВсеПредметы));
                }
            }
        }
    }
}
