//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Rating
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Предмет направление.
    /// </summary>
    // *** Start programmer edit section *** (ПредметНаправление CustomAttributes)

    // *** End programmer edit section *** (ПредметНаправление CustomAttributes)
    [AutoAltered()]
    [Caption("Предмет направление")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ПредметНаправлениеE", new string[] {
            "Направление as \'Направление\'",
            "ВсеПредметы as \'Все предметы\'"})]
    [MasterViewDefineAttribute("ПредметНаправлениеE", "Направление", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Название")]
    [MasterViewDefineAttribute("ПредметНаправлениеE", "ВсеПредметы", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Название")]
    [View("ПредметНаправлениеL", new string[] {
            "Направление.Название as \'Направление\'",
            "ВсеПредметы.Название as \'Предмет\'"})]
    public class ПредметНаправление : ICSSoft.STORMNET.DataObject
    {
        
        private IIS.Rating.Направление fНаправление;
        
        private IIS.Rating.ВсеПредметы fВсеПредметы;
        
        // *** Start programmer edit section *** (ПредметНаправление CustomMembers)

        // *** End programmer edit section *** (ПредметНаправление CustomMembers)

        
        /// <summary>
        /// Предмет направление.
        /// </summary>
        // *** Start programmer edit section *** (ПредметНаправление.Направление CustomAttributes)

        // *** End programmer edit section *** (ПредметНаправление.Направление CustomAttributes)
        [PropertyStorage(new string[] {
                "Направление"})]
        [NotNull()]
        public virtual IIS.Rating.Направление Направление
        {
            get
            {
                // *** Start programmer edit section *** (ПредметНаправление.Направление Get start)

                // *** End programmer edit section *** (ПредметНаправление.Направление Get start)
                IIS.Rating.Направление result = this.fНаправление;
                // *** Start programmer edit section *** (ПредметНаправление.Направление Get end)

                // *** End programmer edit section *** (ПредметНаправление.Направление Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПредметНаправление.Направление Set start)

                // *** End programmer edit section *** (ПредметНаправление.Направление Set start)
                this.fНаправление = value;
                // *** Start programmer edit section *** (ПредметНаправление.Направление Set end)

                // *** End programmer edit section *** (ПредметНаправление.Направление Set end)
            }
        }
        
        /// <summary>
        /// Предмет направление.
        /// </summary>
        // *** Start programmer edit section *** (ПредметНаправление.ВсеПредметы CustomAttributes)

        // *** End programmer edit section *** (ПредметНаправление.ВсеПредметы CustomAttributes)
        [PropertyStorage(new string[] {
                "ВсеПредметы"})]
        [NotNull()]
        public virtual IIS.Rating.ВсеПредметы ВсеПредметы
        {
            get
            {
                // *** Start programmer edit section *** (ПредметНаправление.ВсеПредметы Get start)

                // *** End programmer edit section *** (ПредметНаправление.ВсеПредметы Get start)
                IIS.Rating.ВсеПредметы result = this.fВсеПредметы;
                // *** Start programmer edit section *** (ПредметНаправление.ВсеПредметы Get end)

                // *** End programmer edit section *** (ПредметНаправление.ВсеПредметы Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПредметНаправление.ВсеПредметы Set start)

                // *** End programmer edit section *** (ПредметНаправление.ВсеПредметы Set start)
                this.fВсеПредметы = value;
                // *** Start programmer edit section *** (ПредметНаправление.ВсеПредметы Set end)

                // *** End programmer edit section *** (ПредметНаправление.ВсеПредметы Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ПредметНаправлениеE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ПредметНаправлениеE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ПредметНаправлениеE", typeof(IIS.Rating.ПредметНаправление));
                }
            }
            
            /// <summary>
            /// "ПредметНаправлениеL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ПредметНаправлениеL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ПредметНаправлениеL", typeof(IIS.Rating.ПредметНаправление));
                }
            }
        }
    }
}
