//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Rating
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Тип документов.
    /// </summary>
    // *** Start programmer edit section *** (ТипДокументов CustomAttributes)

    // *** End programmer edit section *** (ТипДокументов CustomAttributes)
    [AutoAltered()]
    [Caption("Тип документов")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ТипДокументовE", new string[] {
            "Название as \'Название\'"})]
    [View("ТипДокументовL", new string[] {
            "Название as \'Название\'"})]
    public class ТипДокументов : ICSSoft.STORMNET.DataObject
    {
        
        private string fНазвание = "Оригинал";
        
        // *** Start programmer edit section *** (ТипДокументов CustomMembers)

        // *** End programmer edit section *** (ТипДокументов CustomMembers)

        
        /// <summary>
        /// Название.
        /// </summary>
        // *** Start programmer edit section *** (ТипДокументов.Название CustomAttributes)

        // *** End programmer edit section *** (ТипДокументов.Название CustomAttributes)
        [StrLen(255)]
        [NotNull()]
        public virtual string Название
        {
            get
            {
                // *** Start programmer edit section *** (ТипДокументов.Название Get start)

                // *** End programmer edit section *** (ТипДокументов.Название Get start)
                string result = this.fНазвание;
                // *** Start programmer edit section *** (ТипДокументов.Название Get end)

                // *** End programmer edit section *** (ТипДокументов.Название Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТипДокументов.Название Set start)

                // *** End programmer edit section *** (ТипДокументов.Название Set start)
                this.fНазвание = value;
                // *** Start programmer edit section *** (ТипДокументов.Название Set end)

                // *** End programmer edit section *** (ТипДокументов.Название Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ТипДокументовE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ТипДокументовE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ТипДокументовE", typeof(IIS.Rating.ТипДокументов));
                }
            }
            
            /// <summary>
            /// "ТипДокументовL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ТипДокументовL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ТипДокументовL", typeof(IIS.Rating.ТипДокументов));
                }
            }
        }
    }
}
