//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Rating
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Форма обучения.
    /// </summary>
    // *** Start programmer edit section *** (ФормаОбучения CustomAttributes)

    // *** End programmer edit section *** (ФормаОбучения CustomAttributes)
    [AutoAltered()]
    [Caption("Форма обучения")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ФормаОбученияE", new string[] {
            "Название as \'Название\'"})]
    [View("ФормаОбученияL", new string[] {
            "Название as \'Название\'"})]
    public class ФормаОбучения : ICSSoft.STORMNET.DataObject
    {
        
        private string fНазвание = "Очная";
        
        // *** Start programmer edit section *** (ФормаОбучения CustomMembers)

        // *** End programmer edit section *** (ФормаОбучения CustomMembers)

        
        /// <summary>
        /// Название.
        /// </summary>
        // *** Start programmer edit section *** (ФормаОбучения.Название CustomAttributes)

        // *** End programmer edit section *** (ФормаОбучения.Название CustomAttributes)
        [StrLen(255)]
        [NotNull()]
        public virtual string Название
        {
            get
            {
                // *** Start programmer edit section *** (ФормаОбучения.Название Get start)

                // *** End programmer edit section *** (ФормаОбучения.Название Get start)
                string result = this.fНазвание;
                // *** Start programmer edit section *** (ФормаОбучения.Название Get end)

                // *** End programmer edit section *** (ФормаОбучения.Название Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ФормаОбучения.Название Set start)

                // *** End programmer edit section *** (ФормаОбучения.Название Set start)
                this.fНазвание = value;
                // *** Start programmer edit section *** (ФормаОбучения.Название Set end)

                // *** End programmer edit section *** (ФормаОбучения.Название Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ФормаОбученияE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ФормаОбученияE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ФормаОбученияE", typeof(IIS.Rating.ФормаОбучения));
                }
            }
            
            /// <summary>
            /// "ФормаОбученияL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ФормаОбученияL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ФормаОбученияL", typeof(IIS.Rating.ФормаОбучения));
                }
            }
        }
    }
}
