<%--flexberryautogenerated="true"--%>
<%@ Page Language="C#" MasterPageFile="~/Site1.Master"  AutoEventWireup="true" CodeBehind="AbiturientE.aspx.cs" Inherits="IIS.Rating.АбитуриентE" %>
<%@ Import namespace="NewPlatform.Flexberry.Web.Page" %>
<%-- Autogenerated section start [Register] --%>
<%-- Autogenerated section end [Register] --%>

<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <div class="<%= Constants.FormCssClass + " " +  Constants.EditFormCssClass %>">
        <h2 class="<%= Constants.FormHeaderCssClass + " " + Constants.EditFormHeaderCssClass %>">Абитуриент</h2>
        <div class="<%= Constants.FormToolbarCssClass  + " " +  Constants.EditFormToolbarCssClass + " " + Constants.StickyCssClass %>">
            <asp:ImageButton ID="SaveBtn" runat="server" SkinID="SaveBtn" OnClick="SaveBtn_Click" AlternateText="<%$ Resources: Resource, Save %>" ValidationGroup="savedoc" />
            <asp:ImageButton ID="SaveAndCloseBtn" runat="server" SkinID="SaveAndCloseBtn" OnClick="SaveAndCloseBtn_Click" AlternateText="<%$ Resources: Resource, Save_Close %>" ValidationGroup="savedoc" />
            <asp:ImageButton ID="CancelBtn" runat="server" SkinID="CancelBtn" OnClick="CancelBtn_Click" AlternateText="<%$ Resources: Resource, Cancel %>" />
        </div>
        <div class="<%= Constants.FormControlsCssClass + " " + Constants.EditFormControlsCssClass %>">
            <%-- Autogenerated section start [Controls] --%>
<!-- autogenerated start -->
<div>
	<div class="clearfix">
  <asp:Label CssClass="descLbl" ID="ctrlФамилияLabel" runat="server" Text="Фамилия" EnableViewState="False">
</asp:Label>
<asp:TextBox CssClass="descTxt" ID="ctrlФамилия" runat="server">
</asp:TextBox>

<asp:RequiredFieldValidator ID="ctrlФамилияRequiredFieldValidator" runat="server" ControlToValidate="ctrlФамилия"
                            ErrorMessage="Не указано: Фамилия" Text="*" 
                            EnableClientScript="true" ValidationGroup="savedoc" />

</div>
<div class="clearfix">
  <asp:Label CssClass="descLbl" ID="ctrlИмяLabel" runat="server" Text="Имя" EnableViewState="False">
</asp:Label>
<asp:TextBox CssClass="descTxt" ID="ctrlИмя" runat="server">
</asp:TextBox>

<asp:RequiredFieldValidator ID="ctrlИмяRequiredFieldValidator" runat="server" ControlToValidate="ctrlИмя"
                            ErrorMessage="Не указано: Имя" Text="*" 
                            EnableClientScript="true" ValidationGroup="savedoc" />

</div>
<div class="clearfix">
  <asp:Label CssClass="descLbl" ID="ctrlОтчествоLabel" runat="server" Text="Отчество" EnableViewState="False">
</asp:Label>
<asp:TextBox CssClass="descTxt" ID="ctrlОтчество" runat="server">
</asp:TextBox>

<asp:RequiredFieldValidator ID="ctrlОтчествоRequiredFieldValidator" runat="server" ControlToValidate="ctrlОтчество"
                            ErrorMessage="Не указано: Отчество" Text="*" 
                            EnableClientScript="true" ValidationGroup="savedoc" />

</div>
<div class="clearfix">
  <asp:Label CssClass="descLbl" ID="ctrlПаспортLabel" runat="server" Text="Паспорт (серия/номер)" EnableViewState="False">
</asp:Label>
<asp:TextBox CssClass="descTxt" ID="ctrlПаспорт" runat="server">
</asp:TextBox>

<asp:RequiredFieldValidator ID="ctrlПаспортRequiredFieldValidator" runat="server" ControlToValidate="ctrlПаспорт"
                            ErrorMessage="Не указано: Паспорт" Text="*" 
                            EnableClientScript="true" ValidationGroup="savedoc" />

</div>
<div class="clearfix">
  <asp:Label CssClass="descLbl" ID="ctrlТелефонLabel" runat="server" Text="Номер телефона" EnableViewState="False">
</asp:Label>
<asp:TextBox CssClass="descTxt" ID="ctrlТелефон" runat="server">
</asp:TextBox>

<asp:RequiredFieldValidator ID="ctrlТелефонRequiredFieldValidator" runat="server" ControlToValidate="ctrlТелефон"
                            ErrorMessage="Не указано: Телефон" Text="*" 
                            EnableClientScript="true" ValidationGroup="savedoc" />

</div>
<div class="clearfix">
  <asp:Label CssClass="descLbl" ID="ctrlСреднийБаллАттестатаLabel" runat="server" Text="Средний балл аттестата" EnableViewState="False">
</asp:Label>
<ac:DecimalTextBox CssClass="descTxt" ID="ctrlСреднийБаллАттестата" runat="server">
</ac:DecimalTextBox>

<asp:RequiredFieldValidator ID="ctrlСреднийБаллАттестатаRequiredFieldValidator" runat="server" ControlToValidate="ctrlСреднийБаллАттестата"
                            ErrorMessage="Не указано: СреднийБаллАттестата" Text="*" 
                            EnableClientScript="true" ValidationGroup="savedoc" />

</div>
<div class="clearfix">
  <asp:Label CssClass="descLbl" ID="ctrlЭссеLabel" runat="server" Text="Эссе" EnableViewState="False">
</asp:Label>
<ac:AlphaNumericTextBox CssClass="descTxt" ID="ctrlЭссе" Type="Numeric" runat="server">
</ac:AlphaNumericTextBox>

<asp:RequiredFieldValidator ID="ctrlЭссеRequiredFieldValidator" runat="server" ControlToValidate="ctrlЭссе"
                            ErrorMessage="Не указано: Эссе" Text="*" 
                            EnableClientScript="true" ValidationGroup="savedoc" />

</div>
<div class="clearfix">
  <asp:Label CssClass="descLbl" ID="ctrlДопБаллыLabel" runat="server" Text="Доп баллы" EnableViewState="False">
</asp:Label>
<ac:AlphaNumericTextBox CssClass="descTxt" ID="ctrlДопБаллы" Type="Numeric" runat="server">
</ac:AlphaNumericTextBox>


</div>

</div>
<!-- autogenerated end -->
            <%-- Autogenerated section end [Controls] --%>
        </div>
    </div>
</asp:Content>
