/*flexberryautogenerated="true"*/
namespace IIS.Rating
{
    using System;
    using ICSSoft.STORMNET.Web.Controls;

    using Resources;

    public partial class НаправлениеL : BaseListForm<Направление>
    {
        /// <summary>
        /// Конструктор без параметров,
        /// инициализирует свойства, соответствующие конкретной форме.
        /// </summary>
        public НаправлениеL() : base(Направление.Views.НаправлениеL)
        {
            EditPage = НаправлениеE.FormPath;
        }
                
        /// <summary>
        /// Путь до формы.
        /// </summary>
        public static string FormPath
        {
            get { return "~/forms/Napravlenie/NapravlenieL.aspx"; }
        }

        /// <summary>
        /// Вызывается самым первым в Page_Load.
        /// </summary>
        protected override void Preload()
        {
        }

        /// <summary>
        /// Вызывается самым последним в Page_Load.
        /// </summary>
        protected override void Postload()
        {
        }
    }
}
