/*flexberryautogenerated="true"*/
namespace IIS.Rating
{
    using System;
    using ICSSoft.STORMNET.Web.Controls;

    using Resources;

    public partial class ПредметНаправлениеL : BaseListForm<ПредметНаправление>
    {
        /// <summary>
        /// Конструктор без параметров,
        /// инициализирует свойства, соответствующие конкретной форме.
        /// </summary>
        public ПредметНаправлениеL() : base(ПредметНаправление.Views.ПредметНаправлениеL)
        {
            EditPage = ПредметНаправлениеE.FormPath;
        }
                
        /// <summary>
        /// Путь до формы.
        /// </summary>
        public static string FormPath
        {
            get { return "~/forms/PredmetNapravlenie/PredmetNapravlenieL.aspx"; }
        }

        /// <summary>
        /// Вызывается самым первым в Page_Load.
        /// </summary>
        protected override void Preload()
        {
        }

        /// <summary>
        /// Вызывается самым последним в Page_Load.
        /// </summary>
        protected override void Postload()
        {
        }
    }
}
